name: CD

on:
  pull_request:
    branches:
      - main
    types:
      - closed   # событие закрытия PR

jobs:
  test-and-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build project
        run: npm run build

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: Manual approval before deploy
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/splitkostya || exit 1
            git pull origin main
            npm install --production
            pm2 restart splitkostya || pm2 start npm --name "splitkostya" -- start
