name: deploy

on:
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    ci-checks:
        if: github.event.pull_request.merged == true
        uses: ./.github/workflows/ci.yml
        secrets: inherit

    deploy-production:
        runs-on: ubuntu-latest
        needs: ci-checks
        if: github.event.pull_request.merged == true
        environment:
            name: production
            url: https://splitcostya.ru
        steps:
            - name: Deploy to production VPS
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      BASE_DIR=/root/banzay/splitKostya
                      APP_NAME="splitKostya"

                      echo "🚀 Deploying to PRODUCTION..."

                      cd $BASE_DIR || exit 1
                      git fetch origin main
                      git reset --hard origin/main
                      git clean -fdx
                      npm install --production
                      npm run build
                      PORT=3000 pm2 restart $APP_NAME || PORT=3000 pm2 start npm --name "$APP_NAME" -- start

    stop-production:
        runs-on: ubuntu-latest
        steps:
            -   name: Stop production app
                uses: appleboy/ssh-action@v0.1.10
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USER }}
                    key: ${{ secrets.VPS_SSH_KEY }}
                    script: |
                        APP_NAME="splitKostya"

                        echo "🛑 Stopping $APP_NAME ..."
                        pm2 stop $APP_NAME || echo "⚠️ $APP_NAME is not running"
